DocterManagement.AdminApp/Controllers/Components/NavMainViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DoctorManagement.AdminApp.Controllers.Components
{
    public class NavMainViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

DocterManagement.AdminApp/Controllers/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DoctorManagement.AdminApp.Controllers.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }

    }
}

DocterManagement.AdminApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="apple-touch-icon" sizes="76x76" href="~/img/News_free-file.png">
	<link rel="icon" type="image/png" href="~/img/News_free-file.png">

	<title>
		Doctor Management
	</title>
	<!-- Extra details for Live View on GitHub Pages -->
	<!-- Canonical SEO -->
	<link rel="canonical" href="https://www.creative-tim.com/product/soft-ui-dashboard-pro" />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
	<!-- Nucleo Icons -->
	<link href="~/css/nucleo-icons.css" rel="stylesheet" />
	<!-- Font Awesome Icons -->
	<script src="~/js/42d5adcbca.js" crossorigin="anonymous"></script>
	<link href="~/css/nucleo-svg.css" rel="stylesheet" />
	<!-- CSS Files -->


	<link href="~/css/soft-ui-dashboard.min.css" rel="stylesheet" />
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<!-- Anti-flicker snippet (recommended)  -->
	<link href="~/css/Style_layout.css" rel="stylesheet" />
	<script src="~/js/plugins/jquery.min.js"></script>
</head>

<body class="g-sidenav-show  bg-gray-100">


	@await Component.InvokeAsync("NavMain")

	<main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
		<!-- Navbar -->

		<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
			<div class="container-fluid py-1 px-3">
				<nav aria-label="breadcrumb">
					@RenderSection("Header", required: false)
				</nav>
				<div class="sidenav-toggler sidenav-toggler-inner d-xl-block d-none ">
					<a href="javascript:;" class="nav-link text-body p-0">
						<div class="sidenav-toggler-inner">
							<i class="sidenav-toggler-line"></i>
							<i class="sidenav-toggler-line"></i>
							<i class="sidenav-toggler-line"></i>
						</div>
					</a>
				</div>
				<div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
					<div class="ms-md-auto pe-md-3 d-flex align-items-center">
						@RenderSection("Search", required: false)
					</div>
					@await Component.InvokeAsync("Navigation")
				</div>
			</div>
		</nav>

		<!-- End Navbar -->
		@RenderBody()

		<footer class="footer pt-3  ">
			<div class="container-fluid">
				<div class="row align-items-center justify-content-lg-between">
					<div class="col-lg-6 mb-lg-0 mb-4">
						<div class="copyright text-center text-sm text-muted text-lg-start">
							©
							<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
							<script>
								document.write(new Date().getFullYear())
							</script>,
							được tạo bởi <i class="fa fa-heart"></i> by
							<a href="#" class="font-weight-bold" target="_blank">Doctor Medical</a>
							để có một trang web tốt hơn.
						</div>
					</div>
					@*<div class="col-lg-6">
						<ul class="nav nav-footer justify-content-center justify-content-lg-end">
							<li class="nav-item">
								<a href="#" class="nav-link text-muted" target="_blank">Team sáng tạo</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link text-muted" target="_blank">Về chúng tôi</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link text-muted" target="_blank">Blog</a>
							</li>
							<li class="nav-item">
								<a href="#" class="nav-link pe-0 text-muted" target="_blank">Giấy phép</a>
							</li>
						</ul>
					</div>*@
				</div>
			</div>
		</footer>
	</main>

	@*<div class="fixed-plugin">
		<a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
			<i class="fa fa-cog py-2"> </i>
		</a>
		<div class="card shadow-lg blur">
			<div class="card-header pb-0 pt-3  bg-transparent ">
				<div class="float-start">
					<h5 class="mt-3 mb-0">Soft UI Configurator</h5>
					<p>See our dashboard options.</p>
				</div>
				<div class="float-end mt-4">
					<button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
						<i class="fa fa-close"></i>
					</button>
				</div>
				<!-- End Toggle Button -->
			</div>
			<hr class="horizontal dark my-1">
			<div class="card-body pt-sm-3 pt-0">
				<!-- Sidebar Backgrounds -->
				<div>
					<h6 class="mb-0">Sidebar Colors</h6>
				</div>
				<a href="javascript:void(0)" class="switch-trigger background-color">
					<div class="badge-colors my-2 text-start">
						<span class="badge filter bg-gradient-primary" data-color="primary" onclick="sidebarColor(this)"></span>
						<span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
						<span class="badge filter bg-gradient-info active" data-color="info" onclick="sidebarColor(this)"></span>
						<span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
						<span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
						<span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
					</div>
				</a>
				<!-- Sidenav Type -->
				<div class="mt-3">
					<h6 class="mb-0">Sidenav Type</h6>
					<p class="text-sm">Choose between 2 different sidenav types.</p>
				</div>
				<div class="d-flex">
					<button class="btn bg-gradient-primary w-100 px-3 mb-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
					<button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
				</div>
				<p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
				<!-- Navbar Fixed -->
				<div class="mt-3">
					<h6 class="mb-0">Navbar Fixed</h6>
				</div>
				<div class="form-check form-switch ps-0">
					<input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
				</div>
				<hr class="horizontal dark mb-1">
				<div class="mt-2">
					<h6 class="mb-0">Sidenav Mini</h6>
				</div>
				<div class="form-check form-switch ps-0">
					<input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarMinimize" onclick="navbarMinimize(this)">
				</div>
				<hr class="horizontal dark my-sm-4">
				<a class="btn bg-gradient-info w-100" href="https://www.creative-tim.com/product/soft-ui-dashboard-pro">Buy now</a>
				<a class="btn bg-gradient-dark w-100" href="https://www.creative-tim.com/product/soft-ui-dashboard">Free demo</a>
				<a class="btn btn-outline-dark w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/overview/soft-ui-dashboard">View documentation</a>
				<div class="w-100 text-center">
					<a class="github-button" href="https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/soft-ui-dashboard on GitHub">Star</a>
					<h6 class="mt-3">Thank you for sharing!</h6>
					<a href="https://twitter.com/intent/tweet?text=Check%20Soft%20UI%20Dashboard%20PRO%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fsoft-ui-dashboard-pro" class="btn btn-dark mb-0 me-2" target="_blank">
						<i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
					</a>
					<a href="https://www.facebook.com/quannguyen.itpro" class="btn btn-dark mb-0 me-2" target="_blank">
						<i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
					</a>
				</div>
			</div>
		</div>
	</div>*@

	<script src="~/js/core/popper.min.js"></script>
	<script src="~/js/core/bootstrap.min.js"></script>
	<script src="~/js/plugins/perfect-scrollbar.min.js"></script>
	<script src="~/js/plugins/smooth-scrollbar.min.js"></script>
	<script src="~/js/plugins/multistep-form.js"></script>
	<script src="~/js/plugins/choices.min.js"></script>
	@RenderSection("jsFooter", required: false)

	<script>
		var win = navigator.platform.indexOf('Win') > -1;
		if (win && document.querySelector('#sidenav-scrollbar')) {
			var options = {
				damping: '0.5'
			}
			Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
		}
	</script>
	<script src="~/js/plugins/jquery.js"></script>
	<script src="~/js/plugins/jquery.min.js"></script>
	<script>
		$(function () {
		   @* $('#AlertBox').removeClass('hide1');*@
			$('#AlertBox').addClass('slideNotify');
			$('#AlertBox').delay(6000).slideUp(500);


		})
	</script>
	<!-- Github buttons -->
	<script async defer src="https://buttons.github.io/buttons.js"></script>
	<!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
	<script src="~/js/soft-ui-dashboard.min.js?v=1.0.3"></script>
	@*@await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>